<a href="https://colab.research.google.com/github/anveshveeramalla/Anvesh_INFO5731_SPRING2022/blob/main/In_class_exercise_03_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (2/22/2022, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Text classification is a machine learning technique that assigns a set of predefined categories to open-ended text. Text classifiers can be used to organize, structure, and categorize pretty much any kind of text â€“ from documents, medical studies and files, and all over the web.

For example, new articles can be organized by topics; support tickets can be organized by urgency; chat conversations can be organized by language; brand mentions can be organized by sentiment; and so on.

Text classification is one of the fundamental tasks in natural language processing with broad applications such as sentiment analysis, topic labeling, spam detection, and intent detection.

In these exercise we have colleceted data of bheemla nayak movie reviews from imdb website and we have calculated including Number of words, Number of characters, Average word lengths, Number of stopwords, Number of special characters, Number of numeric,
and Number of uppercase words.




'''

Question 2 (20 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [11]:

# You code here (Please add comments in the code):
#importing requried packages
import nltk

from bs4 import BeautifulSoup as bs
import pandas as pd
import requests as rq
import matplotlib.pyplot as plt
import nltk
from wordcloud import WordCloud
from nltk.corpus import stopwords


#collecting sample text data from IMDb "BheemlaNaik movie reviews"

#assigining the URL to a varilable 
url = 'https://www.imdb.com/title/tt14209560/reviews?ref_=tt_ov_rt'

#Creating a data frame with one column to store text of reviews
data_frame = pd.DataFrame(columns=['Review'])
req = rq.get(url).text
soup = bs(req,'html.parser')

#collecting reviews text
review_text = soup.find_all('div', attrs={'class' : 'text show-more__control'})

#creating a empty list
review_list = []
for i in range(len(review_text)):
    review_list.append(review_text[i].get_text())

#assigining list to the data frame    
data_frame['Review'] = review_list

data_frame['word_count'] = data_frame['Review'].apply(lambda x: len(str(x).split(" ")))
data_frame[['Review','word_count']].head()

                                              Review  word_count
0  Telugu screenplay is is a bit fast. Intervel s...         115
1  Whenever there's a remake announced and Pawan ...         174
2  One can say that bad movies of PSPK could be w...         325
3  Fantastic movie. Perfectly balanced both chara...          54
4  This is a failed attempt to remake a successfu...          45

In [3]:
#Number of characters

data_frame['char_count'] = data_frame['Review'].str.len() ## this also includes spaces
data_frame[['Review','char_count']].head()

                                              Review  char_count
0  Telugu screenplay is is a bit fast. Intervel s...         683
1  Whenever there's a remake announced and Pawan ...        1045
2  One can say that bad movies of PSPK could be w...        1858
3  Fantastic movie. Perfectly balanced both chara...         340
4  This is a failed attempt to remake a successfu...         246

In [5]:
#Average word lengths
def avg_word(sentence):
  words = sentence.split()
  return (sum(len(word) for word in words)/len(words))

  data_frame['avg_word'] = data_frame['Review'].apply(lambda x: avg_word(x))
data_frame[['Review','avg_word']].head()

                                              Review  avg_word
0  Telugu screenplay is is a bit fast. Intervel s...  4.947826
1  Whenever there's a remake announced and Pawan ...  5.011494
2  One can say that bad movies of PSPK could be w...  4.720000
3  Fantastic movie. Perfectly balanced both chara...  5.314815
4  This is a failed attempt to remake a successfu...  4.488889

In [6]:
#Number of stopwords

from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')
stop = stopwords.words('english')

data_frame['stopwords'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x in stop]))
data_frame[['Review','stopwords']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                              Review  stopwords
0  Telugu screenplay is is a bit fast. Intervel s...         49
1  Whenever there's a remake announced and Pawan ...         73
2  One can say that bad movies of PSPK could be w...        118
3  Fantastic movie. Perfectly balanced both chara...         18
4  This is a failed attempt to remake a successfu...         16

In [7]:
#Number of special characters
data_frame['hastags'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
data_frame[['Review','hastags']].head()

                                              Review  hastags
0  Telugu screenplay is is a bit fast. Intervel s...        0
1  Whenever there's a remake announced and Pawan ...        0
2  One can say that bad movies of PSPK could be w...        0
3  Fantastic movie. Perfectly balanced both chara...        0
4  This is a failed attempt to remake a successfu...        0

In [8]:
#Number of numerics

data_frame['numerics'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
data_frame[['Review','numerics']].head()

                                              Review  numerics
0  Telugu screenplay is is a bit fast. Intervel s...         0
1  Whenever there's a remake announced and Pawan ...         0
2  One can say that bad movies of PSPK could be w...         0
3  Fantastic movie. Perfectly balanced both chara...         0
4  This is a failed attempt to remake a successfu...         0

In [9]:
#Number of uppercase words

data_frame['upper'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
data_frame[['Review','upper']].head()

                                              Review  upper
0  Telugu screenplay is is a bit fast. Intervel s...      0
1  Whenever there's a remake announced and Pawan ...      2
2  One can say that bad movies of PSPK could be w...      8
3  Fantastic movie. Perfectly balanced both chara...      0
4  This is a failed attempt to remake a successfu...      1

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [12]:
# You code here (Please add comments in the code):


tf1 = (data_frame['Review'][1:2]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
tf1.columns = ['words','tf']
tf1

          words  tf
0           the  14
1           and  10
2            of   4
3          will   4
4            to   3
..          ...  ..
126    dynamic,   1
127       power   1
128  imbalanced   1
129          an   1
130   original.   1

[131 rows x 2 columns]

In [13]:
#ITF
import numpy as np

for i,word in enumerate(tf1['words']):
  tf1.loc[i, 'idf'] = np.log(data_frame.shape[0]/(len(data_frame[data_frame['Review'].str.contains(word)])))

tf1

          words  tf       idf
0           the  14  0.328504
1           and  10  0.446287
2            of   4  0.510826
3          will   4  1.609438
4            to   3  0.174353
..          ...  ..       ...
126    dynamic,   1  3.218876
127       power   1  1.832581
128  imbalanced   1  3.218876
129          an   1  0.083382
130   original.   1  1.139434

[131 rows x 3 columns]

In [14]:
#TF-IDF
tf1['tfidf'] = tf1['tf'] * tf1['idf']
tf1

          words  tf       idf     tfidf
0           the  14  0.328504  4.599057
1           and  10  0.446287  4.462871
2            of   4  0.510826  2.043302
3          will   4  1.609438  6.437752
4            to   3  0.174353  0.523060
..          ...  ..       ...       ...
126    dynamic,   1  3.218876  3.218876
127       power   1  1.832581  1.832581
128  imbalanced   1  3.218876  3.218876
129          an   1  0.083382  0.083382
130   original.   1  1.139434  1.139434

[131 rows x 4 columns]